name: hello-world
on:
  push:
  workflow_dispatch:
    inputs:
      provertype:
        description: 'invoke real vs mock prover'
        required: true
        default: 'mock_prover'
        type: choice
        options:
        - real_prover
        - mock_prover

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-instance-type:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.type }}

    steps:
      - id: step1
        name: Bla-1
        run: |
          echo "type=c5.12xlarge" >> $GITHUB_OUTPUT
          echo ${{ github.event.inputs.provertype }}

  prepare-env:
    needs: [set-instance-type]
    steps:
      - env:
          OUTPUT1: ${{needs.step1.outputs.output1}}
        run: echo bla
    runs-on: ["${{github.run_id}}", self-hosted, "$OUTPUT1"]
