name: hello-world

on:
  push:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare-env:
    runs-on: ubuntu-latest

    steps:
      - name: sayhi
        run: echo "Hello World!"
      - name: sleep
        run: sleep 10
