name: hello-world
on:
  push:
  workflow_dispatch:
    inputs:
      provertype:
        description: 'invoke real vs mock prover'
        required: true
        default: 'mock_prover'
        type: choice
        options:
        - real_prover
        - mock_prover

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-instance-type:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.type }}

    steps:
      - id: step1
        name: Bla-1
        if: ${{ github.event.inputs.provertype == 'real_prover' }}
        run: echo "type=c5.12xlarge" >> $GITHUB_OUTPUT

  prepare-env:
    needs: [set-instance-type]
    runs-on: [ubuntu-latest, $OUTPUT1]

    steps:
      - env:
          OUTPUT1: ${{ needs.set-instance-type.outputs.output1 }}
        run: echo "$OUTPUT1"
