name: hello-world

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare-env:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 

  my-job:
    needs: prepare-env
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: integration-tests

    steps:
      - name: sayhi
        run: echo "Hello World!"
      - name: sleep
        run: sleep 10
