name: hello-world
on:
  push:
  workflow_dispatch:
    inputs:
      provertype:
        description: 'invoke real vs mock prover'
        required: true
        default: 'mock_prover'
        type: choice
        options:
        - real_prover
        - mock_prover

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.prepare-instance-type.outputs.type }}
    steps:
      - id: prepare-instance-type
        name: prepare-instance-type
        run: |
          if [ "${{ github.event.inputs.provertype }}" = "mock_prover" ] || [ -z ${{ github.event.inputs.provertype }} ]; then
            echo "type=c5.9xlarge" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.event.inputs.provertype }}" = "real_prover" ]; then
            echo "type=c5.24xlarge" >> "$GITHUB_OUTPUT"
          else
            exit 1
          fi  

  job2:
    runs-on: ["${{ github.run_id }}", self-hosted, "${{ needs.prepare-instance-type.outputs.output1 }}"]
    #runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Drill
        run: echo "$OUTPUT1"
