name: hello-world
on:
  push:
  workflow_dispatch:
    inputs:
      provertype:
        description: 'invoke real vs mock prover'
        required: true
        default: 'mock_prover'
        type: choice
        options:
        - real_prover
        - mock_prover

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-type:
    runs-on: ubuntu-latest

    steps:
      - name: sayhi
        run: |
          echo $env.provertype

  prepare-env:
    needs: [set-type]
    runs-on: ubuntu-latest

    steps:
      - name: sayhi
        run: echo "Hello World!"
      - name: sleep
        run: sleep 10
