name: hello-world

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  type: ubuntu-latest

jobs:
  prepare-env:
    runs-on: ${{ type }}

    steps:
      - name: sayhi
        run: echo "Hello World!"
      - name: sleep
        run: sleep 10
