name: hello-world
on:
  push:
  workflow_dispatch:
    inputs:
      provertype:
        description: 'invoke real vs mock prover'
        required: true
        default: 'mock_prover'
        type: choice
        options:
        - real_prover
        - mock_prover

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-instance-type:
    runs-on: ubuntu-latest

    steps:
      - name: Check-real
        if: ${{ env.provertype == 'real_prover' }}
        run: type="c5.9xlarge"
      - name: sayhi
        run: |
          echo $day!
          echo $day
          echo ${{ github.event.inputs.provertype }}

  prepare-env:
    needs: [set-type]
    runs-on: ubuntu-latest

    steps:
      - name: sayhi
        run: echo "Hello World!"
      - name: sayho
        run: echo "$github.jobs.set-instance-type.steps.type"
