name: Integration Tests

on:
  merge_group:
  schedule:
    - cron: '50 1 * * SUN'
  pull_request:
    types: [synchronize, labeled]
  push:
    branches:
      - main
  workflow_dispatch:    
    inputs:
      provertype:
        description: 'invoke real vs mock prover'
        required: true
        default: 'mock_prover'
        type: choice
        options:
        - real_prover
        - mock_prover  

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    if: github.event.pull_request.draft == false

    name: Integration Tests
    runs-on: ["${{github.run_id}}", self-hosted, x1e.4xlarge]

    steps:
      - name: Set provertype to mock_prover for push & pull_request_labelled
        run: |
          echo "provertype=mock_prover" >> $GITHUB_ENV
        if: github.event_name == 'push' ||
            github.event_name == 'pull_request'
      - name: Set provertype to workflow_dispatch choice
        run: |
          echo "provertype=${{ inputs.provertype }}" >> $GITHUB_ENV
        if: github.event_name == 'workflow_dispatch'
      - name: Set provertype to real_prover for scheduled runs
        run: |
          echo "provertype=real_prover" >> $GITHUB_ENV
        if: github.event_name == 'schedule'
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: false
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: ~1.18
      # Go cache for building geth-utils
      - name: Go cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Cargo cache
        uses: actions/cache@v3  
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      # Run an initial build in a separate step to split the build time from execution time    
      - name: Build bins
        run: cargo build --bin gen_blockchain_data
      - name: Build tests
        run: for testname in rpc circuit_input_builder circuits; do cargo test --profile release --test $testname --features $testname --no-run; done
      - run: ./run.sh --steps "setup"
        working-directory: integration-tests
      - run: ./run.sh --steps "gendata"
        working-directory: integration-tests
      - run: ./run.sh --steps "tests" --tests "rpc"
        working-directory: integration-tests
      - run: ./run.sh --steps "tests" --tests "circuit_input_builder"
        working-directory: integration-tests
      - run: RUST_TEST_THREADS=1 ./run.sh --steps "tests" --tests "circuits::${{ env.provertype }}"
        working-directory: integration-tests
      - run: ./run.sh --steps "cleanup"
        working-directory: integration-tests
